# Generated by Django 5.x

import apps.documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=127)),
                ("file_size", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="UPLOADED",
                        max_length=16,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner", "status"], name="doc_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["created_at"], name="doc_created_at_idx"),
        ),
    ]
